apiVersion: v1
kind: Secret
metadata:
  name: switchbot-credentials
  namespace: default
type: Opaque
data:
  # Base64 encoded SwitchBot API token
  token: "your-token"  # your-switchbot-token
  # Base64 encoded SwitchBot API secret
  secret: "eW91ci1zd2l0Y2hib3Qtc2VjcmV0"  # your-switchbot-secret