apiVersion: thermo-pilot.yadon3141.com/v1
kind: ThermoPilot
metadata:
  labels:
    app.kubernetes.io/name: thermo-pilot-controller
    app.kubernetes.io/managed-by: kustomize
  name: thermopilot-sample
spec:
  secretRef:
    name: switchbot-credentials
    tokenKey: token
    secretKey: secret
  # airConditionerId: "02-202509160308-19770636"  # Optional - if not specified, controls all air conditioners
  temperatureSensorType: MeterPro
  targetTemperature: "25.0"
  threshold: "1.0"
  mode: cool
